-- MySQL Script generated by MySQL Workbench
-- Mon Dec 23 18:47:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origen` VARCHAR(255) NOT NULL,
  `precio` INT NOT NULL,
  `destino` VARCHAR(255) NOT NULL,
  `salida` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `disponible` TINYINT NOT NULL,
  `viaje_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asiento_viaje1_idx` (`viaje_id` ASC) VISIBLE,
  CONSTRAINT `fk_asiento_viaje1`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pasaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pasaje` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asiento_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pasaje_asiento1_idx` (`asiento_id` ASC) VISIBLE,
  INDEX `fk_pasaje_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pasaje_asiento1`
    FOREIGN KEY (`asiento_id`)
    REFERENCES `asiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasaje_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
